name: Social Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-social:
    runs-on: ubuntu-latest
    steps:
      - uses: AllenCheng5186/social-readme@main
        with:
          blog_rss_link: https://studywithallen.com/feed/
          blog_limit: 5 
          repository: AllenCheng5186/AllenCheng5186
